# Generated by Django 2.2.7 on 2020-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
    ]
