# Generated by Django 2.2.7 on 2020-11-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200715_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='threshold',
            field=models.IntegerField(default=50),
        ),
    ]
