# Generated by Django 2.2.7 on 2020-11-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='threshold',
        ),
    ]
